[package]
name = "libc"
version = "0.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "libc"
path = "../../liblibc/src/lib.rs"
test = false
bench = false
doc = false

[features]
# Certain parts of libc are conditionally compiled differently than when used
# outside rustc. See https://github.com/rust-lang/libc/search?l=Rust&q=stdbuild&type=&utf8=%E2%9C%93.
stdbuild = []
default = ["stdbuild", "align"]
align = []
